name: Dependent Workflow

on:
  push

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['8', '10', '12']

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm version
      run: |
        echo NPM Version ${{  matrix.node_version }}
